fix(1863): add unassigned activity log logic
Nuvalence/dsgov-web pull request #435
Opened 2023-09-20 17:11 UTC by jgnuvalence

# Basics

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Styling and layout changes
- [ ] Code style changes (formatting, local variables)
- [ ] Refactoring (no functional changes)
- [ ] Build or CI related changes
- [ ] Tests
- [ ] Other... Please describe:

## What changes does this PR introduce?

## Screenshot of the affected changes

## Accessibility report

## Checklist

- [ ] I have updated the documentation accordingly
- [ ] I have confirmed all acceptance criteria defined by the story have been met
- [ ] I have confirmed that Sonar Qube findings for new code are reviewed and fixed, or will be whitelisted

2023-09-20 18:52 UTC, odeljanin requested changes

2023-09-20 18:52 UTC, odeljanin commented on libs/agency/feature/dashboard/src/lib/components/events-log/events-log.component.ts
> +          event.summary = `${await firstValueFrom(this._userStateService.getUserDisplayName$(event.requestContext?.userId || ''))} unassigned this application`;
Summary does not match the acceptance criteria

2023-09-20 19:23 UTC, jgnuvalence commented
> @jgnuvalence the code looks good but the summary does not match the acceptance criteria added by @asultan001

Hey @abarnanuvalence, I think it's good to know who unassigned the transaction, do you agree?, I can changes this otherwise

2023-09-20 19:24 UTC, jgnuvalence commented on libs/agency/feature/dashboard/src/lib/components/events-log/events-log.component.ts
> +          event.summary = `${await firstValueFrom(this._userStateService.getUserDisplayName$(event.requestContext?.userId || ''))} unassigned this application`;
Hey @asultan001 , I think it's good to know who unassigned the transaction, do you agree?, I can changes this otherwise

2023-09-20 21:07 UTC, davidyoung77 approved these changes
Thanks, if we don't hear otherwise from Abe, about the comment lets merge this like you have it

2023-09-20 21:07 UTC, davidyoung77 commented on libs/agency/feature/dashboard/src/lib/components/events-log/events-log.component.ts
> +          event.summary = `${await firstValueFrom(this._userStateService.getUserDisplayName$(event.requestContext?.userId || ''))} unassigned this application`;
I agree with you here, as it also matches what we are doing for the assigned activity

2023-09-20 21:07 UTC, davidyoung77 approved these changes

2023-09-21 14:00 UTC, odeljanin commented on libs/agency/feature/dashboard/src/lib/components/events-log/events-log.component.ts
> +          event.summary = `${await firstValueFrom(this._userStateService.getUserDisplayName$(event.requestContext?.userId || ''))} unassigned this application`;
I believe what Abe is referring to is that we already know who unassigned the transaction. The person who performed the action is mentioned below the title, alongside the date. This information seems redundant. However, I agree we should probably match with the assign event. If we intend to remove the name of the initial person who performed the action because it's already stated along with the date, we should consider doing it in both scenarios.

2023-09-21 14:14 UTC, asultan001 commented on libs/agency/feature/dashboard/src/lib/components/events-log/events-log.component.ts
> +          event.summary = `${await firstValueFrom(this._userStateService.getUserDisplayName$(event.requestContext?.userId || ''))} unassigned this application`;
Hey guys, thanks for thinking this through and aiming for consistency across the different audit events. My original intent was as Omer described given the info is redundant but we can keep it consistent. If the code is good we can push this forward as is.

2023-09-21 14:23 UTC, odeljanin approved these changes

2023-09-21 16:15 UTC, merged