Dsg 1397/handle loading states
Nuvalence/dsgov-web pull request #438
Opened 2023-09-21 17:33 UTC by SouradeepSaha

# Basics

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [x] Styling and layout changes
- [ ] Code style changes (formatting, local variables)
- [ ] Refactoring (no functional changes)
- [ ] Build or CI related changes
- [ ] Tests
- [ ] Other... Please describe:

## What changes does this PR introduce?

- Change layout of spinner on button
- Fix agency dashboard not showing spinner while initial load
- Fix location of spinner overlapping with table header on agency dashboard
- Add faded blur effect while spinner is loading

## Screenshot of the affected changes
<img width="376" alt="Screenshot 2023-09-21 at 1 31 32 PM" src="https://github.com/Nuvalence/dsgov-web/assets/46139736/042548e3-8c7f-48fe-9afc-980a07d11b40">

<img width="1046" alt="Screenshot 2023-09-21 at 1 33 04 PM" src="https://github.com/Nuvalence/dsgov-web/assets/46139736/0a1fad7f-02aa-4458-ab1b-a6b4589c0ecd">

<img width="1046" alt="Screenshot 2023-09-21 at 1 32 18 PM" src="https://github.com/Nuvalence/dsgov-web/assets/46139736/c3d51832-ca62-40fc-acbd-9538a3a54103">

## Accessibility report

## Checklist

- [x] I have updated the documentation accordingly
- [x] I have confirmed all acceptance criteria defined by the story have been met
- [ ] I have confirmed that Sonar Qube findings for new code are reviewed and fixed, or will be whitelisted

2023-09-22 04:46 UTC, davidyoung77 requested changes
Thanks I have a handful of comments

2023-09-22 04:46 UTC, davidyoung77 commented on libs/shared/ui/nuverial/src/lib/components/spinner/spinner.component.scss
> +  }
A couple comments here
- overlay might be a better contextual name
- I believe this css will do better at what you are wanting to do

```suggestion
  .overlay {
    background-color: white;
    position: fixed;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
    opacity: 0.3;
  }
```

2023-09-22 04:46 UTC, davidyoung77 commented on libs/shared/ui/nuverial/src/lib/components/spinner/spinner.component.html
> +<div class="whiten-background"></div>
This can be enabled by default but we should have a way to disable it probably with an ngIf and an @input

2023-09-22 04:46 UTC, davidyoung77 commented on libs/shared/ui/nuverial/src/lib/components/button/button.component.scss
> +:host-context(.dsg-authentication-email-content-controls) {
Giving this parent class specificity her isn't the best way to handle this, a better way to do this is to apply a class to the button called `has-loading` and use that class here in the host context

2023-09-22 04:46 UTC, davidyoung77 commented on libs/agency/feature/dashboard/src/lib/components/transactions-list/transactions-list.component.scss
> +      margin-top: -120px;
Does this work better if we add the `position

2023-09-22 13:58 UTC, SouradeepSaha commented on libs/shared/ui/nuverial/src/lib/components/spinner/spinner.component.scss
> +  }
Sure! `overlay` seems to be a better name, however this is the result of applying the new css, i.e. the overlay does not work:
<img width="1046" alt="Screenshot 2023-09-22 at 9 56 37 AM" src="https://github.com/Nuvalence/dsgov-web/assets/46139736/3cc56913-397e-47df-9c89-2afabf31fac2">

2023-09-22 15:47 UTC, SouradeepSaha commented on libs/shared/ui/nuverial/src/lib/components/spinner/spinner.component.html
> +<div class="whiten-background"></div>
Done

2023-09-22 17:48 UTC, SouradeepSaha commented on libs/agency/feature/dashboard/src/lib/components/transactions-list/transactions-list.component.scss
> +      margin-top: -120px;
Done

2023-09-25 18:08 UTC, davidyoung77 reviewed
I'd like to pair on the positioning

2023-09-25 18:08 UTC, davidyoung77 commented on libs/shared/ui/nuverial/src/lib/components/button/button.component.scss
> +:host-context(.dsg-authentication-email-content-controls) {
This still isn't reusable nameing

2023-09-25 18:08 UTC, davidyoung77 commented on libs/shared/ui/nuverial/src/lib/components/spinner/spinner.component.scss
> +  }
We can look together fixed position should handle this well

2023-09-26 21:14 UTC, davidyoung77 commented
this branch has become corrupt best to start a new branch and cherrypick in your changes

example: `git cherry-pick --no-commit #commitHash`

2023-09-27 17:41 UTC, SouradeepSaha commented
Closed in favor of new PR: https://github.com/Nuvalence/dsgov-web/pull/458

2023-09-27 17:41 UTC, closed without merging