Feat/dsg-1572/enumsStateService
Nuvalence/dsgov-web pull request #440
Opened 2023-09-22 07:27 UTC by Ortega-Dan

This reverts commit f68cb62a4fd29a53a48776da39ce9d4fe6df8056.

# Basics

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Styling and layout changes
- [ ] Code style changes (formatting, local variables)
- [ ] Refactoring (no functional changes)
- [ ] Build or CI related changes
- [ ] Tests
- [ ] Other... Please describe:

## What changes does this PR introduce?

## Screenshot of the affected changes

## Accessibility report

## Checklist

- [ ] I have updated the documentation accordingly
- [ ] I have confirmed all acceptance criteria defined by the story have been met
- [ ] I have confirmed that Sonar Qube findings for new code are reviewed and fixed, or will be whitelisted

2023-09-22 19:20 UTC, davidyoung77 reviewed
I started review and have a few comments I will review more later

2023-09-22 19:20 UTC, davidyoung77 commented on libs/shared/feature/app-state/src/lib/services/enumerations-state/enumerations-state.service.ts
> +  }
ngondestroy is a component thing

2023-09-22 19:20 UTC, davidyoung77 commented on libs/shared/feature/app-state/src/lib/services/enumerations-state/enumerations-state.service.ts
> +      .subscribe();
We should handle the sub and the cleanup in the auth, ideally with a switch map or similar

2023-09-22 22:12 UTC, Ortega-Dan commented on libs/shared/feature/app-state/src/lib/services/enumerations-state/enumerations-state.service.ts
> +  }
haha. Thanks

2023-09-22 22:13 UTC, Ortega-Dan commented on libs/shared/feature/app-state/src/lib/services/enumerations-state/enumerations-state.service.ts
> +      .subscribe();
This is following the pattern of user state in auth service. 
The cleanup is also handled like that now.
Thank you.

2023-09-26 03:16 UTC, davidyoung77 requested changes
Thanks I have a few comments

2023-09-26 03:16 UTC, davidyoung77 commented on libs/agency/feature/dashboard/src/lib/components/events-log/event-types/document-status-changed/document-status-changed.component.ts
> +      this._enumService
Same here, the async pipe and rxjs map would simplify this, or using a syncronous get method

2023-09-26 03:16 UTC, davidyoung77 commented on libs/agency/feature/dashboard/src/lib/components/events-log/event-types/document-status-changed/document-status-changed.component.ts
> -        this.rejectedReasons.push(RejectedReasonLabels[rejectedReason]);
did the RejectedReasonLabels get remove? please confirm

2023-09-26 03:16 UTC, davidyoung77 commented on libs/shared/feature/app-state/src/lib/services/enumerations-state/enumerations-state.service.ts
> +  public getValueFromEnum$(enumKey: EnumMapType, id: string): Observable<string> {
We should add a syncrounous get method that can be used if needed, for ease of use, you can do this easily by converting the subject to a behaviorSubject which gives access to the value

2023-09-26 03:16 UTC, davidyoung77 commented on libs/shared/feature/app-state/src/lib/services/enumerations-state/enumerations-state.service.ts
> +  private readonly enums$ = this.enumsSubject.asObservable();
I'm curious why our linting isn't failing here, our linting encourages naming of an underscore prefix for private fields.

2023-09-26 03:16 UTC, davidyoung77 commented on libs/shared/feature/app-state/src/lib/services/enumerations-state/enumerations-state.service.ts
We should add documenting comments, with usage details to each of these service methods. The public ones at least

2023-09-26 03:16 UTC, davidyoung77 commented on libs/agency/feature/dashboard/src/lib/components/notes/notes.component.ts
> +        this._enumsService
This would be simpler either using the async pipe, or a syncronous get method from the service

2023-09-26 13:01 UTC, Ortega-Dan commented on libs/agency/feature/dashboard/src/lib/components/events-log/event-types/document-status-changed/document-status-changed.component.ts
> -        this.rejectedReasons.push(RejectedReasonLabels[rejectedReason]);
Yes. It was removed even before you did this comment. Not sure how it showed in your review, but it is not here, and not even in an entire project search

2023-09-26 13:05 UTC, Ortega-Dan commented on libs/shared/feature/app-state/src/lib/services/enumerations-state/enumerations-state.service.ts
> +  private readonly enums$ = this.enumsSubject.asObservable();
Right, adjusted.

2023-09-26 13:59 UTC, Ortega-Dan commented on libs/shared/feature/app-state/src/lib/services/enumerations-state/enumerations-state.service.ts
Implemented

2023-09-26 14:16 UTC, Ortega-Dan commented on libs/agency/feature/dashboard/src/lib/components/notes/notes.component.ts
> +        this._enumsService
Applied the approach, we anyway need to deal with what happens if the data is not initialized yet due to a slow internet connection after a hard reload. The change considers that approach.

2023-09-26 14:19 UTC, Ortega-Dan commented on libs/agency/feature/dashboard/src/lib/components/events-log/event-types/document-status-changed/document-status-changed.component.ts
> +      this._enumService
It simplifies it as an initial writing, but we then anyway need to call the async methods, restoring the not wanted complexity, and increasingly by the previous sync call, to deal with the situations in which the data is not yet initialized, like in a hard reload with a slow connection.

2023-09-26 14:21 UTC, Ortega-Dan commented on libs/agency/feature/dashboard/src/lib/components/documents-review/documents-review.component.ts
> +    this._enumService
same as previous comments, what if it is not available.

2023-09-26 14:26 UTC, Ortega-Dan commented on libs/agency/feature/dashboard/src/lib/components/documents-review/documents-review.component.html
> +            <li *ngFor="let reason of document.rejectionReasons; let i = index; trackBy: trackByFn">{{$any(rejectedReasonsLabels)?.[reason]}}</li>
yes. done

2023-09-26 14:28 UTC, Ortega-Dan commented on libs/agency/feature/dashboard/src/lib/components/documents-review/documents-review.component.html
> +            <li *ngFor="let reason of document.rejectionReasons; let i = index; trackBy: trackByFn">{{$any(rejectedReasonsLabels)?.[reason]}}</li>
also the rejectedReasonsLabels is initialized to a default value. So the save navigation is also not needed as recommended by tsc

2023-09-26 14:58 UTC, Ortega-Dan commented on libs/agency/feature/dashboard/src/lib/components/documents-review/documents-review.component.html
> +            <li *ngFor="let reason of document.rejectionReasons; let i = index; trackBy: trackByFn">{{$any(rejectedReasonsLabels)?.[reason]}}</li>
Talking to david. this comes better with the Observer.

2023-09-26 15:21 UTC, Ortega-Dan commented on libs/agency/feature/dashboard/src/lib/components/documents-review/documents-review.component.ts
> +    this._enumService
This is the ts code preserved then in order to deal with the situation in which data is not initialized yet. Like in a hard reload with slow response.

2023-09-26 15:39 UTC, Ortega-Dan commented on libs/agency/feature/dashboard/src/lib/components/notes/notes.component.ts
> +        this._enumsService
According to previous determination with David on things that are not able to that easily use the async pipe, we are keeping the code subscription way.

2023-09-26 17:51 UTC, davidyoung77 reviewed
reviewed together left 1 comment

2023-09-26 17:51 UTC, davidyoung77 commented on libs/agency/feature/dashboard/src/lib/components/notes/note-form/note-form.component.ts
> +    this._enumService
will convert to async pipe

2023-09-26 18:20 UTC, Ortega-Dan commented on libs/agency/feature/dashboard/src/lib/components/documents-review/documents-review.component.ts
> +    this._enumService
On our discussion, we changed the one for the select options to async which is higher to this comment. but this stays since it is only for the labels mapper.

2023-09-26 18:22 UTC, Ortega-Dan commented on libs/agency/feature/dashboard/src/lib/components/events-log/event-types/document-status-changed/document-status-changed.component.ts
> +      this._enumService
This one statys as the refactoring is more difficult and the current implementation abides to how it was working first. Some of the reasons are that this mapping is to be used by the data, and the data must first taken away into a variable in order to use it in the template, but instead of being in a variable it is being parsed from a string in this method some lines above of this code.

2023-09-26 18:23 UTC, Ortega-Dan commented on libs/agency/feature/dashboard/src/lib/components/notes/note-form/note-form.component.ts
> +    this._enumService
Converted to async pipe.

2023-09-26 18:25 UTC, Ortega-Dan commented on libs/agency/feature/dashboard/src/lib/components/notes/notes.component.ts
> +        this._enumsService
This was rather to go the lines of the implementation how it was before. and this call doesn't have to depend on the getting on the notes, so it was moved to the ngOnInit

2023-09-26 18:28 UTC, davidyoung77 approved these changes

2023-09-26 19:18 UTC, davidyoung77 approved these changes

2023-09-26 19:21 UTC, davidyoung77 approved these changes

2023-09-26 19:34 UTC, merged