Dsg 1659/update note form
Nuvalence/dsgov-web pull request #441
Opened 2023-09-22 13:31 UTC by lanamckay

# Basics

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [X] Styling and layout changes
- [X] Code style changes (formatting, local variables)
- [ ] Refactoring (no functional changes)
- [ ] Build or CI related changes
- [X] Tests
- [ ] Other... Please describe:

## What changes does this PR introduce?
Use the form errors component to show invalid input to users 

## Screenshot of the affected changes

<img width="1261" alt="Screenshot 2023-09-22 at 9 30 25 AM" src="https://github.com/Nuvalence/dsgov-web/assets/84589636/5a81a3d1-15b9-42d6-ac38-e087ed8d08ad">
<img width="884" alt="Screenshot 2023-09-22 at 9 30 46 AM" src="https://github.com/Nuvalence/dsgov-web/assets/84589636/f7034511-c2aa-4874-8dc0-0285a6facdaf">

## Accessibility report

## Checklist

- [ ] I have updated the documentation accordingly
- [ ] I have confirmed all acceptance criteria defined by the story have been met
- [ ] I have confirmed that Sonar Qube findings for new code are reviewed and fixed, or will be whitelisted

2023-09-22 15:48 UTC, odeljanin requested changes
Thanks, I've left some comments

2023-09-22 15:48 UTC, odeljanin commented on libs/agency/feature/dashboard/src/lib/components/notes/note-form/note-form.component.html
> +    <header *ngIf="showErrorHeader"><nuverial-form-errors [formErrors]="formErrors"></nuverial-form-errors></header>
We can use the array `formErrors` instead in here and remove this boolean. Let's have the condition to check if theres any errors

2023-09-22 15:48 UTC, odeljanin commented on libs/agency/feature/dashboard/src/lib/components/notes/note-form/note-form.component.spec.ts
> +    it('should set formErrors and showErrorHeader when form is invalid', () => {
It would be good to add a spy in this test to verify that the `createNote$` function was not called when the form is invalid.

2023-09-22 15:48 UTC, odeljanin commented on libs/agency/feature/dashboard/src/lib/components/notes/note-form/note-form.component.ts
> +  public showErrorHeader = false;
This boolean can be removed when the condition in the HTML is updated to check the array instead

2023-09-22 15:48 UTC, odeljanin commented on libs/agency/feature/dashboard/src/lib/components/notes/note-form/note-form.component.ts
> +    if (this.noteFormGroup.valid) {
let's refactor this to 
```suggestion
    if (!this.noteFormGroup.valid) {
      this.formErrors = HandleFormErrors(this.noteFormGroup, this.formConfigs);
      MarkAllControlsAsTouched(this.noteFormGroup);
      return;
    }
```

so we don't need to wrap the whole function in a if else

2023-09-22 15:48 UTC, odeljanin commented on libs/shared/ui/nuverial/src/lib/components/form-errors/form-errors.component.html
> +  <li class="show-more" *ngIf="formErrors.length > 3">
Seems like you duplicated this code by mistake? I see the same code on line 17

2023-09-22 15:48 UTC, odeljanin commented on libs/shared/ui/nuverial/src/lib/components/form-errors/form-errors.model.ts
> +  const formErrors1 = Object.entries(GetAllFormErrors(formGroup) || []).map(([controlName, errorName]) => {
```suggestion
  const formErrors = Object.entries(GetAllFormErrors(formGroup) || []).map(([controlName, errorName]) => {
```

2023-09-25 18:26 UTC, davidyoung77 requested changes
Thanks, I have a few comments

2023-09-25 18:26 UTC, davidyoung77 commented on libs/agency/feature/dashboard/src/lib/components/notes/note-form/note-form.component.html
> +    <header *ngIf="formErrors.length > 0"><nuverial-form-errors [formErrors]="formErrors"></nuverial-form-errors></header>
This should be sufficient

```suggestion
    <header *ngIf="formErrors.length"><nuverial-form-errors [formErrors]="formErrors"></nuverial-form-errors></header>
```

2023-09-25 18:26 UTC, davidyoung77 commented on libs/agency/feature/dashboard/src/lib/components/notes/note-form/note-form.component.ts
> +  /* eslint-disable sort-keys */
Rather than disabling, can you sort the keys?
vscode sort plugin works well to do this

2023-09-25 18:26 UTC, davidyoung77 commented on libs/shared/ui/nuverial/src/lib/components/form-errors/form-errors.component.spec.ts
> +    expect(document.querySelector).toHaveBeenCalledWith('#1234 input');
nice test here

2023-09-25 18:26 UTC, davidyoung77 commented on libs/shared/ui/nuverial/src/lib/components/form-errors/form-errors.model.ts
> +export const HandleFormErrors = (formGroup: AbstractControl | null, formErrorsConfig: Record<string, FormErrorsConfiguration>): IFormError[] => {
We should give this a better name, maybe `FormErrorsFromGroup`

2023-09-25 19:15 UTC, lanamckay commented on libs/agency/feature/dashboard/src/lib/components/notes/note-form/note-form.component.ts
> +  /* eslint-disable sort-keys */
Hi @davidyoung77, thanks for the comments!

When I sort the keys the order of the errors aren't displayed in the correct order they appear, as shown below:
<img width="983" alt="Screenshot 2023-09-25 at 3 10 00 PM" src="https://github.com/Nuvalence/dsgov-web/assets/84589636/583ceac7-5c18-4f4d-b451-2ba397f562e3">

Whereas, when I disable the sort-keys, I can display the errors in the correct order they appear, as shown below:
<img width="1734" alt="Screenshot 2023-09-22 at 9 40 54 AM" src="https://github.com/Nuvalence/dsgov-web/assets/84589636/5ebdf69c-99f6-4dfa-8ac9-6fa0aeeabcf7">

I thought the second option was a bit more user-friendly but I am open to your suggestion. Thank you!

2023-09-26 02:00 UTC, davidyoung77 approved these changes
Thanks approved

2023-09-26 02:02 UTC, davidyoung77 commented
@odeljanin I dismissed you review as I need this code for my work and your comments have been resolved

2023-09-26 02:04 UTC, merged