Dsg 80/ability to create and edit a form configuration
Nuvalence/dsgov-web pull request #443
Opened 2023-09-22 14:37 UTC by g8shen

# Basics

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Styling and layout changes
- [ ] Code style changes (formatting, local variables)
- [ ] Refactoring (no functional changes)
- [ ] Build or CI related changes
- [ ] Tests
- [ ] Other... Please describe:

## What changes does this PR introduce?

## Screenshot of the affected changes

## Accessibility report

## Checklist

- [ ] I have updated the documentation accordingly
- [ ] I have confirmed all acceptance criteria defined by the story have been met
- [ ] I have confirmed that Sonar Qube findings for new code are reviewed and fixed, or will be whitelisted

2023-09-30 04:17 UTC, davidyoung77 reviewed
Thanks i have a handful of comments

2023-09-30 04:17 UTC, davidyoung77 commented on libs/shared/data-access/work-api/src/lib/models/form/form.model.ts
> +  public name?: string | null = '';
These should all be like this, empty string should be there empty value
```suggestion
  public name = '';
```

2023-09-30 04:17 UTC, davidyoung77 commented on libs/shared/data-access/work-api/src/lib/models/transaction-metadata/transaction-metadata.model.ts
> +  public name?: string | null = '';
```suggestion
  public name: string = '';
```

2023-09-30 04:17 UTC, davidyoung77 commented on libs/shared/data-access/work-api/src/lib/models/transaction-metadata/transaction-metadata.model.ts
> +  public toFormioBuilderForm(): FormioForm {
I don't think you need this, as it is not part of the form metadata

2023-09-30 04:17 UTC, davidyoung77 commented on libs/shared/feature/form-nuv/src/lib/components/forms/builder/form-builder.component.ts
> +      this.formKey = params.get('formKey') ?? '';
why not include these in the metadata observable and leave them private here?

2023-09-30 04:17 UTC, davidyoung77 commented on libs/shared/feature/form-nuv/src/lib/components/forms/builder/form-builder.service.ts
> +    .pipe(map(formConfigurationModel => structuredClone(formConfigurationModel.toSchema())));
I don't believe you need the map in this case.

this looks like copy pasta, I could be wrong.

For the other cases we are using it in 3 separate places, which is why we do that

2023-09-30 04:17 UTC, davidyoung77 commented on libs/shared/feature/form-nuv/src/lib/components/forms/header/builder-header.component.scss
> +}
I don't think you need this here, this looks like copy pasta from the form builder component

2023-09-30 04:17 UTC, davidyoung77 commented on libs/shared/feature/form-nuv/src/lib/components/forms/header/builder-header.component.spec.ts
> +
lets add the accessibility test, this can be seen in many of our other tests, search spec files for accessibility for example

2023-10-03 15:46 UTC, davidyoung77 requested changes
Thanks just a couple comments

2023-10-03 16:29 UTC, g8shen commented on libs/shared/data-access/work-api/src/lib/services/work-api-routes.service.ts
> +        });
Added the fields to the IActiveForms interface then added the spread at the start so that configuration could override our spread and give the value that we want

2023-10-03 18:59 UTC, davidyoung77 approved these changes
Nice work thanks

2023-10-03 19:15 UTC, merged