Dsg 1660/update profile
Nuvalence/dsgov-web pull request #465
Opened 2023-10-02 18:07 UTC by lanamckay

# Basics

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [x] Styling and layout changes
- [ ] Code style changes (formatting, local variables)
- [ ] Refactoring (no functional changes)
- [ ] Build or CI related changes
- [ ] Tests
- [ ] Other... Please describe:

## What changes does this PR introduce?
Incorporates Form Errors component into profile updates

## Screenshot of the affected changes

Before:
<img width="1780" alt="Screenshot 2023-10-02 at 2 06 12 PM" src="https://github.com/Nuvalence/dsgov-web/assets/84589636/3c0ba489-399d-479a-94d5-a2914b4155b0">
After:
<img width="1777" alt="Screenshot 2023-10-02 at 2 06 29 PM" src="https://github.com/Nuvalence/dsgov-web/assets/84589636/e229e8a8-a589-4797-92e5-4aa71aff20e2">
<img width="1769" alt="Screenshot 2023-10-02 at 2 06 37 PM" src="https://github.com/Nuvalence/dsgov-web/assets/84589636/dad02271-e5d8-4b5a-a862-272db6a293bb">

## Accessibility report

## Checklist

- [ ] I have updated the documentation accordingly
- [ ] I have confirmed all acceptance criteria defined by the story have been met
- [ ] I have confirmed that Sonar Qube findings for new code are reviewed and fixed, or will be whitelisted

2023-10-02 19:29 UTC, asultan001 commented on libs/public/feature/profile/src/lib/components/profile/profile.component.ts
> +export class ProfileComponent {
@davidyoung77 does this approach make this harder to localize?

2023-10-02 19:32 UTC, asultan001 commented on libs/shared/ui/nuverial/src/lib/components/checkbox/checkbox.component.spec.ts
Why comment out all of these tests?

2023-10-02 19:42 UTC, lanamckay commented on libs/shared/ui/nuverial/src/lib/components/checkbox/checkbox.component.spec.ts
Hi @asultan001, those three tests were failing with my updated code.
Please see new commit with the updated tests, thanks!

2023-10-02 20:35 UTC, davidyoung77 commented on libs/public/feature/profile/src/lib/components/profile/profile.component.ts
> +export class ProfileComponent {
This is good for now, we will strongly define the localization patterns in the work I am doing this sprint

2023-10-02 20:44 UTC, davidyoung77 requested changes
This needs more work, I have dm'd you

2023-10-02 20:44 UTC, davidyoung77 commented on libs/shared/ui/nuverial/src/lib/components/checkbox/checkbox.component.html
> +<div class="nuverial-checkbox-card-container" [ngClass]="{'image-position-before': imagePosition === 'before'}">
This is wrong, I have DM'd you

2023-10-02 20:44 UTC, davidyoung77 commented on libs/shared/ui/nuverial/src/lib/components/checkbox/checkbox.component.spec.ts
These changes are likely related to the component file updates above and will change once that is fixed

2023-10-02 20:44 UTC, davidyoung77 commented on libs/shared/ui/nuverial/src/lib/components/checkbox/checkbox.component.ts
> +  /**
why these additions?

2023-10-02 21:10 UTC, lanamckay commented on libs/shared/ui/nuverial/src/lib/components/checkbox/checkbox.component.ts
> +  /**
These changes were related to the component file.
Please see updated commit

2023-10-02 21:12 UTC, lanamckay commented on libs/shared/ui/nuverial/src/lib/components/checkbox/checkbox.component.spec.ts
Tests work as expected with the updated html file

2023-10-02 21:27 UTC, davidyoung77 requested changes

2023-10-02 21:27 UTC, davidyoung77 commented on libs/shared/ui/nuverial/src/lib/components/checkbox-card/checkbox-card-async.component.spec.ts
I believe these changes are un-intentional

2023-10-02 21:27 UTC, davidyoung77 commented on libs/shared/ui/nuverial/src/lib/components/checkbox/checkbox.component.ts
I'd like to see a unit test, testing the implementation here that we are using in the profile component (we discussed this in our meeting today)

We should be sure to check that the dom is updated properly in the test

2023-10-03 15:24 UTC, lanamckay commented on libs/shared/ui/nuverial/src/lib/components/checkbox/checkbox.component.ts
Currently in progress.
As discussed in stand up, I have created a subtask for this.

2023-10-03 15:53 UTC, davidyoung77 approved these changes

2023-10-03 17:21 UTC, davidyoung77 approved these changes

2023-10-03 18:04 UTC, merged