dsg 641/dsg 1981: creating new transaction definition pages
Nuvalence/dsgov-web pull request #487
Opened 2023-10-06 19:42 UTC by derekdiep42

# Basics

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Styling and layout changes
- [x] Code style changes (formatting, local variables)
- [ ] Refactoring (no functional changes)
- [ ] Build or CI related changes
- [x] Tests
- [ ] Other... Please describe:

## What changes does this PR introduce?

Story: https://dol-ewf.atlassian.net/browse/DSG-641

This PR implements the ADDING/CREATION portion of the transaction definition page. This connects to the + add transaction flow/button implemented on my previous PR. 

TO NOTE
- the route to this page is currently 'admin/transaction-defintions/new', this can be up for discussion
- this does NOT refer to the edit page yet (OR ERROR HANDLING), will be covered in the next PRs
- ended up contacting czara for breadcrumb expectations, this is what we decided on

## Screenshot of the affected changes

Page:
<img width="1543" alt="Screenshot 2023-10-06 at 3 37 16 PM" src="https://github.com/Nuvalence/dsgov-web/assets/56942479/38331a65-5653-4ea1-ab5a-216936c680e0">

Creation process:
https://github.com/Nuvalence/dsgov-web/assets/56942479/02e49032-46f8-490b-a08b-28da43094be6

Form validation/errors.

https://github.com/Nuvalence/dsgov-web/assets/56942479/f310f254-c272-49c8-90bd-06ce302c6830

Breadcrumb/navigation:

https://github.com/Nuvalence/dsgov-web/assets/56942479/0847df64-2813-4444-b509-b42047910301

## Accessibility report

## Checklist

- [ ] I have updated the documentation accordingly
- [x] I have confirmed all acceptance criteria defined by the story have been met
- [ ] I have confirmed that Sonar Qube findings for new code are reviewed and fixed, or will be whitelisted

2023-10-06 20:18 UTC, Ortega-Dan commented on libs/agency/feature/admin/src/lib/components/transaction-definitions-form/transaction-definitions-form.component.ts
> +    this._router.navigate(['../'], { relativeTo: this._activatedRoute });
I believe it is better to be explicit, in case routes change. And also test this redirection also with the explicit path.

2023-10-06 20:21 UTC, Ortega-Dan commented on libs/agency/feature/admin/src/lib/components/transaction-definitions-form/transaction-definitions-form.component.spec.ts
> +    component.onActionClick('cancel');
as with my previous comment I would test the redirection really happens when the method is called.

2023-10-06 20:25 UTC, Ortega-Dan reviewed
.

2023-10-06 20:26 UTC, Ortega-Dan requested changes
Made some comments.

2023-10-06 21:00 UTC, Ortega-Dan commented
@derekdiep42 I also noticed the breadcrumb looks gray but it is not like that in Figma. Was this agreed upon with @czara5  ?

2023-10-06 21:13 UTC, Ortega-Dan commented
> @derekdiep42 I also noticed the breadcrumb looks gray but it is not like that in Figma. Was this agreed upon with @czara5 ?

I wondered about the grayish breadcrumb. but I know now that @derekdiep42 talk about with @czara5 and that it is fine, and the designs are going to be updated to match that. 
Thanks.

2023-10-10 14:40 UTC, davidyoung77 approved these changes
Approved pending a couple minor comments

2023-10-10 16:58 UTC, davidyoung77 commented on libs/agency/feature/admin/src/lib/components/transaction-definitions-form/transaction-definitions-form.component.ts
> +      x.items.forEach(schemaDefinition => {
Can we just map here rather than creating a new array?

2023-10-10 16:58 UTC, davidyoung77 commented on libs/agency/feature/admin/src/lib/components/transaction-definitions-form/transaction-definitions-form.component.ts
> +  public workflowOptions$: Observable<INuverialSelectOption[]> = this._workApiRoutesService.getWorkflowsList$(this.pagingRequestModel).pipe(
Can we just map here rather than creating a new array?

2023-10-10 17:59 UTC, merged