Dsg-1839/toggle between visual and json
Nuvalence/dsgov-web pull request #503
Opened 2023-10-12 18:24 UTC by g8shen

# Basics

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Styling and layout changes
- [ ] Code style changes (formatting, local variables)
- [ ] Refactoring (no functional changes)
- [ ] Build or CI related changes
- [ ] Tests
- [ ] Other... Please describe:

## What changes does this PR introduce?

## Screenshot of the affected changes

## Accessibility report

## Checklist

- [ ] I have updated the documentation accordingly
- [ ] I have confirmed all acceptance criteria defined by the story have been met
- [ ] I have confirmed that Sonar Qube findings for new code are reviewed and fixed, or will be whitelisted

2023-10-12 18:53 UTC, jgnuvalence commented
LGTM however I prefer to have this reviewed by David or Omer before being approved

2023-10-17 18:22 UTC, davidyoung77 requested changes
Thanks, I have a few changes

2023-10-17 18:22 UTC, davidyoung77 commented on package.json
> +    "jsoneditor": "^9.10.3",
Is jsoneditor a dependency of ang-jsoneditor?

2023-10-17 18:22 UTC, davidyoung77 commented on libs/shared/ui/theme/index.scss
> +@import '~jsoneditor/dist/jsoneditor.min.css';
Lets actually only do this in the builder where it is being used, no need to import accross the whole app

2023-10-17 18:22 UTC, davidyoung77 commented on libs/shared/feature/form-nuv/src/lib/components/forms/builder/form-builder.component.ts
> +  public onSelectEvent(event: string): void {
onSelectEvent is pretty generic, maybe `onTabSelect`

2023-10-17 18:22 UTC, davidyoung77 commented on libs/shared/feature/form-nuv/src/lib/components/forms/builder/form-builder.component.ts
> +  public initEditorOptions() {
```suggestion
  public initJsonEditorOptions() {
```

2023-10-17 18:22 UTC, davidyoung77 commented on libs/shared/feature/form-nuv/src/lib/components/forms/builder/form-builder.component.ts
> +  public editorOptions!: JsonEditorOptions;
```suggestion
  public jsonEditorOptions!: JsonEditorOptions;
```

2023-10-17 18:29 UTC, g8shen commented on package.json
> +    "jsoneditor": "^9.10.3",
Yes I believe it will not work if I do not include jsoneditor. I will remove jsoneditor and re test this.

2023-10-17 18:30 UTC, g8shen commented on libs/shared/feature/form-nuv/src/lib/components/forms/builder/form-builder.component.ts
> +  schemas: [NO_ERRORS_SCHEMA],
Without this I couldn't bind anything to ang-json-editor inputs and couldn't find another solution

2023-10-18 09:22 UTC, g8shen commented on package.json
> +    "jsoneditor": "^9.10.3",
I have verified that jsoneditor is a dependency of ang-jsoneditor and the application will not serve if I do not include it.

2023-10-18 09:27 UTC, g8shen commented on libs/shared/feature/form-nuv/src/lib/components/forms/builder/form-builder.component.ts
> +  schemas: [NO_ERRORS_SCHEMA],
Perhaps CUSTOM_ELEMENTS_SCHEMA is better here? For more context the compiler throws errors when importing and trying to access the json-editor. CUSTOM_ELEMENTS_SCHEMA allows custom elements with proper naming convention (dash-case) whileas NO_ERRORS_SCHEMA just ignores unrecognized. Please let me know if this is acceptable or if I should find another solution.

2023-10-18 09:30 UTC, g8shen commented on libs/shared/ui/theme/index.scss
> +@import '~jsoneditor/dist/jsoneditor.min.css';
The styles do not seem to apply when I move it to where the builder is being used. I tried moving it to the builders scss file. Please let me know if this isn't what you had in mind or if I should spend time finding a solution to make importing it only where do builder is being used work. Thanks.

2023-10-18 16:26 UTC, davidyoung77 requested changes
A couple comments, we met and discussed

2023-10-18 16:26 UTC, davidyoung77 commented on libs/shared/ui/theme/index.scss
> +@import '~jsoneditor/dist/jsoneditor.min.css';
I will work with you we can keep this in the place it is used

2023-10-18 16:26 UTC, davidyoung77 commented on libs/shared/feature/form-nuv/src/lib/components/forms/builder/form-builder.component.ts
> +  schemas: [CUSTOM_ELEMENTS_SCHEMA],
We can't merge like this?

2023-10-18 21:25 UTC, davidyoung77 approved these changes

2023-10-18 22:19 UTC, davidyoung77 approved these changes

2023-10-18 22:19 UTC, davidyoung77 approved these changes

2023-10-18 23:07 UTC, davidyoung77 approved these changes

2023-10-18 23:28 UTC, merged