feat(dsg-1828): new form configuration
Nuvalence/dsgov-web pull request #536
Opened 2023-10-23 18:19 UTC by lanamckay

# Basics

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Styling and layout changes
- [ ] Code style changes (formatting, local variables)
- [ ] Refactoring (no functional changes)
- [ ] Build or CI related changes
- [x] Tests
- [ ] Other... Please describe:

## What changes does this PR introduce?
Users can now create new form configurations from the transaction definition page.

## Screenshot of the affected changes
<img width="596" alt="Screenshot 2023-10-24 at 12 49 34 PM" src="https://github.com/Nuvalence/dsgov-web/assets/84589636/daea0cf1-97aa-4329-86ae-e1601b68cbfe">

## Accessibility report

## Checklist

- [ ] I have updated the documentation accordingly
- [ ] I have confirmed all acceptance criteria defined by the story have been met
- [ ] I have confirmed that Sonar Qube findings for new code are reviewed and fixed, or will be whitelisted

2023-10-23 19:46 UTC, lanamckay commented
Currently writing unit tests to fix build

2023-10-24 21:15 UTC, derekdiep42 requested changes
Can you also confirm the edit nodal still works?

2023-10-24 21:15 UTC, derekdiep42 commented on libs/shared/feature/form-nuv/src/lib/components/forms/transaction-definition-metadata/transaction-definition-metadata.component.ts
> +      mode: new FormControl(this.metaData?.mode),
I don't think we need the mode in the formgroup, it's only used for managing the submit data.

2023-10-24 21:15 UTC, derekdiep42 commented on libs/shared/feature/form-nuv/src/lib/components/forms/transaction-definition-metadata/transaction-definition-metadata.component.ts
> +      schemaKey: new FormControl(this.metaData?.schemaKey),
I think schemaKey has to exist for this to work right? Maybe return or error if schemaKey is not provided? @davidyoung77 @jgnuvalence

2023-10-24 21:15 UTC, derekdiep42 commented on libs/shared/feature/form-nuv/src/lib/components/forms/transaction-definition-metadata/transaction-definition-metadata.component.ts
> +    const formKeyFormControl = new FormControl(this.metaData?.formKey);
this for sure needs validation like name, on update atleast

2023-10-24 21:15 UTC, derekdiep42 commented on libs/shared/data-access/work-api/src/lib/models/form/form.model.ts
> +  mode?: 'Create' | 'Update';
Again, we can use the create/update enum I showed you before here, and everywhere else that has the bare string 'create' or 'update'.

Unless someone else said otherwise, I think it's better we use that enum.

2023-10-24 21:15 UTC, derekdiep42 commented on libs/agency/feature/admin/src/lib/components/form-configurations/form-configurations.component.ts
> +    private readonly cdr: ChangeDetectorRef,
I think we should leave this as _cdr? All the other ones are underscored.

2023-10-24 22:22 UTC, jgnuvalence commented on libs/shared/feature/form-nuv/src/lib/components/forms/transaction-definition-metadata/transaction-definition-metadata.component.ts
> +      mode: new FormControl(this.metaData?.mode),
you are right @derekdiep42 , @lanamckay can you remove it?

2023-10-24 22:39 UTC, jgnuvalence requested changes

2023-10-24 22:39 UTC, jgnuvalence commented on libs/agency/feature/admin/src/lib/components/form-configurations/form-configurations.component.ts
> +    private readonly cdr: ChangeDetectorRef,
yes, private attributes should start with underscored

2023-10-24 22:39 UTC, jgnuvalence commented on libs/shared/data-access/work-api/src/lib/models/form/form.model.ts
> +  mode?: 'Create' | 'Update';
I have seen this pattern in many other parts of the app and I think it is fine for cases with few options like this one that only has 2 cases, the important thing is to restrict the values that can be given to mode, just opinion

2023-10-24 22:39 UTC, jgnuvalence commented on libs/shared/feature/form-nuv/src/lib/components/forms/transaction-definition-metadata/transaction-definition-metadata.component.ts
> +    const formKeyFormControl = new FormControl(this.metaData?.formKey);
I agree, let's add:
[Validators.maxLength(200), Validators.required]

2023-10-24 22:39 UTC, jgnuvalence commented on libs/agency/feature/admin/src/lib/components/form-configurations/form-configurations.component.ts
> +          location.reload();
I assume that you are refreshing the page so that the item of the newly saved form configuration is shown in the list of the ui, but this is not desirable, what you should do is add the item in `formConfigurationTableData` when it is confirmed that it has been saved successfully as a response from the backend

2023-10-24 22:39 UTC, jgnuvalence commented on libs/shared/feature/form-nuv/src/lib/components/forms/transaction-definition-metadata/transaction-definition-metadata.component.ts
> +      schemaKey: new FormControl(this.metaData?.schemaKey),
yes schemaKey is mandatory, don't remove the validation

2023-10-24 23:54 UTC, derekdiep42 commented on libs/shared/data-access/work-api/src/lib/models/form/form.model.ts
> +  mode?: 'Create' | 'Update';
@jgnuvalence I recently just added this enum to manage the create/update for transaction definitions too. I feel like it could be a good add here, but up to you!

2023-10-25 20:46 UTC, jgnuvalence commented on libs/agency/feature/admin/src/lib/components/form-configurations/form-configurations.component.ts
> +          location.reload();
@lanamckay I tested this in my local and I see the formKey is not being set to the table automatically after a form config is created:
![image](https://github.com/Nuvalence/dsgov-web/assets/97063738/bedbc301-e108-4cee-a0f0-d224408ee855)

2023-10-26 14:10 UTC, jgnuvalence approved these changes

2023-10-26 14:22 UTC, derekdiep42 approved these changes
LGTM 🫡

2023-10-26 14:22 UTC, merged