DSG-2129/Sync-Json-editor-with-form-builder
Nuvalence/dsgov-web pull request #556
Opened 2023-10-30 21:29 UTC by SouradeepSaha

# Basics

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Styling and layout changes
- [ ] Code style changes (formatting, local variables)
- [ ] Refactoring (no functional changes)
- [ ] Build or CI related changes
- [ ] Tests
- [ ] Other... Please describe:

## What changes does this PR introduce?

Introduces two-way binding between the Json editor and the Form builder 

## Screenshot of the affected changes

Before:

https://github.com/Nuvalence/dsgov-web/assets/46139736/3aeef3c8-fc52-43cc-a4f5-888b1351a4e7

After:

https://github.com/Nuvalence/dsgov-web/assets/46139736/e25bbff7-3f65-421f-ac0d-477193b1be36

## Accessibility report

## Checklist

- [ ] I have updated the documentation accordingly
- [ ] I have confirmed all acceptance criteria defined by the story have been met
- [ ] I have confirmed that Sonar Qube findings for new code are reviewed and fixed, or will be whitelisted

2023-10-31 17:18 UTC, davidyoung77 requested changes
Thanks I have a change

2023-10-31 17:18 UTC, davidyoung77 commented on libs/shared/feature/form-nuv/src/lib/components/forms/builder/form-builder.component.ts
> +    this.formio$ = of(formComponents);
Rather than doing this here, we should maintain state in the service, we have the public method `this.updateFormRendering` in the component that you should be able to use

2023-11-02 15:38 UTC, derekdiep42 requested changes
nice work, just some comments

2023-11-02 15:38 UTC, derekdiep42 commented on libs/shared/ui/nuverial/src/lib/components/json-editor/json-editor.component.ts
> +  @Output() public readonly jsonChange = new EventEmitter<object>();
Add a description to this just like the input above. Refer to other @Output() descriptions.

2023-11-02 15:38 UTC, derekdiep42 commented on libs/shared/feature/form-nuv/src/lib/components/forms/builder/form-builder.component.ts
> +    this.editedJson = formComponents;
I would actually consider moving updateFormRendering here. Right now if the preview pane is open, if you make edits to the json, it won't actually change the contents in the pane until you switch back? I'm not sure if this is what we want. Is this possible to have active updates?

cc: @davidyoung77

2023-11-02 15:38 UTC, derekdiep42 commented on libs/shared/ui/nuverial/src/lib/components/json-editor/json-editor.component.ts
> +  public editedJson = this.formioJSONObject;
We don't need this right?  Just use `this.formioJSONObject` in the emit.

2023-11-02 15:38 UTC, derekdiep42 commented on libs/shared/ui/nuverial/src/lib/components/json-editor/json-editor.component.ts
> +    this.jsonEditorOptions.onChangeText = json => {
we can probably add this to the existing init options test

2023-11-02 15:38 UTC, derekdiep42 commented on libs/shared/feature/form-nuv/src/lib/components/forms/builder/form-builder.component.ts
> +    this.updateFormRendering(formComponents);
Referring to the comment under, if we have it there then maybe we don't need it here? I'm not complete sure, just try testing around because I think we want json changes to be reactive.

2023-11-02 15:42 UTC, derekdiep42 commented on libs/shared/feature/form-nuv/src/lib/components/forms/builder/form-builder.component.ts
> +    this.editedJson = formComponents;
Talked to @SouradeepSaha about it but it seems like active rerendering isn't possible without the cursor resetting to the start of the editor. This means when the preview pane is open, it won't have active updates. Not sure a workout for this. @davidyoung77 @asultan001

2023-11-02 15:47 UTC, SouradeepSaha commented on libs/shared/feature/form-nuv/src/lib/components/forms/builder/form-builder.component.ts
> +    this.updateFormRendering(formComponents);
Same as previous response

2023-11-02 15:55 UTC, davidyoung77 reviewed
I have a few followup comments thanks

2023-11-02 15:55 UTC, davidyoung77 commented on libs/shared/feature/form-nuv/src/lib/components/forms/builder/form-builder.component.html
> +              (selectEvent)="currentSelectorTab === selectorTabs[0].key ? onTabSelect($event, form) : onTabSelect($event, editedJson)"
This would be more future proof if you use an enum for this conditional, and you can update the selectorTabs to use the enum also

```suggestion
              (selectEvent)="currentSelectorTab === SelectorKeys.MY_KEY ? onTabSelect($event, form) : onTabSelect($event, editedJson)"
```

2023-11-02 15:55 UTC, davidyoung77 commented on libs/shared/feature/form-nuv/src/lib/components/forms/builder/form-builder.component.ts
> +        switchMap(() => this._formBuilderService.builderFormFields$),
I don't think you need this here anymore

2023-11-02 15:55 UTC, davidyoung77 commented on libs/shared/feature/form-nuv/src/lib/components/forms/builder/form-builder.component.ts
> +        untilDestroyed(this),
Correct me if I am wrong but I believe you are only interested in the first response here, in which case `take(1) is what you want

2023-11-03 14:53 UTC, davidyoung77 approved these changes
Hey a few minor comments left and this is good, thanks

2023-11-03 14:53 UTC, davidyoung77 commented on libs/shared/feature/form-nuv/src/lib/components/forms/builder/form-builder.component.ts
> +  public jsonForm: Record<string, unknown> = {};
I believe the correct type is `IFormConfigurationSchema[]`

```suggestion
  public jsonForm: Record<string, unknown> = {};
```

2023-11-03 15:26 UTC, davidyoung77 commented on libs/shared/feature/form-nuv/src/lib/components/forms/builder/form-builder.component.ts
> +    this.updateFormRendering(formComponents);
One more thing, do the json editor emit changes immediately or does it debounce?

if it doesn't we will need to debounce here

example https://stackoverflow.com/questions/39959102/how-do-i-debounce-the-output-of-an-inner-component

2023-11-03 15:59 UTC, davidyoung77 approved these changes

2023-11-03 16:01 UTC, derekdiep42 approved these changes
nice work, just some comments

2023-11-03 16:01 UTC, merged