dsg-1668: json editor for schema definition forms
Nuvalence/dsgov-web pull request #635
Opened 2023-11-15 18:21 UTC by derekdiep42

# Basics

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Styling and layout changes
- [ ] Code style changes (formatting, local variables)
- [ ] Refactoring (no functional changes)
- [ ] Build or CI related changes
- [ ] Tests
- [ ] Other... Please describe:

## What changes does this PR introduce?

Notice how in the upper left you can expand to see the Schema definition as a JSON viewer. This editor will allow for the creation of the schema by hand editing the code. Additionally it will allow users to simply copy and paste the schema for basic non visual editing.  

Implements
- JSON toggle button
- JSON -> schema tree translation for dynamic JSON editing
- Code clean up and reorganizing schema builder

## Screenshot of the affected changes

Video of toggling and editing:

https://github.com/Nuvalence/dsgov-web/assets/56942479/0ee90c5c-5b1d-4bd4-ada7-a528c5a95317

Video that editing the form changes the json + saving:

https://github.com/Nuvalence/dsgov-web/assets/56942479/ab14f43e-9e92-4188-b253-95f4f7489aa6

## Accessibility report

## Checklist

- [ ] I have updated the documentation accordingly
- [x] I have confirmed all acceptance criteria defined by the story have been met
- [ ] I have confirmed that Sonar Qube findings for new code are reviewed and fixed, or will be whitelisted

2023-11-15 18:23 UTC, derekdiep42 commented on libs/shared/feature/schema-nuv/src/lib/components/forms/builder/schema-builder.component.ts
> +      component.change
Not completely sure if this part is needed, but I saw it was in form builder. I think it helps with less calls to updateFormRendering, so I added it here as well.

2023-11-15 19:05 UTC, davidyoung77 commented on libs/shared/feature/schema-nuv/src/lib/components/forms/builder/schema-builder.component.ts
> +      component.change
Yes we need this to handle detecting formio changes

2023-11-15 19:07 UTC, davidyoung77 approved these changes
Looks good

2023-11-15 19:13 UTC, SouradeepSaha requested changes

2023-11-15 19:13 UTC, SouradeepSaha commented on libs/shared/feature/schema-nuv/src/lib/components/forms/builder/schema-builder.component.html
> +            <section class="nuverial-json-editor" *ngSwitchCase="selectorTabs[1].key">
I'd suggest what David suggested me to do as well, which is to create an Enum for better code readability instead of using array indices

2023-11-16 17:51 UTC, davidyoung77 commented on libs/shared/feature/schema-nuv/src/lib/components/forms/builder/schema-builder.component.html
> +            <section class="nuverial-json-editor" *ngSwitchCase="selectorTabs[1].key">
good catch @SouradeepSaha

2023-11-16 18:18 UTC, davidyoung77 commented on libs/shared/feature/schema-nuv/src/lib/components/forms/builder/schema-builder.service.ts
> +        }),
Add `take(1)` here please

2023-11-16 18:23 UTC, davidyoung77 reviewed
I have one comment then this will be good

2023-11-16 18:23 UTC, davidyoung77 commented on libs/shared/feature/schema-nuv/src/lib/components/forms/builder/schema-builder.service.ts
> +      .subscribe();
It is a good practice in most cases to handle the subscription in the component. can you move the subscribe to the component? also add take(1) to prevent any memory leaks

2023-11-16 18:32 UTC, davidyoung77 approved these changes

2023-11-16 19:11 UTC, g8shen approved these changes

2023-11-16 19:11 UTC, merged

2023-11-16 19:11 UTC, SouradeepSaha approved these changes