feat(DSG 2459): Employer Edit form
Nuvalence/dsgov-web pull request #725
Opened 2023-12-13 21:20 UTC by thechechogomez

# Basics

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Styling and layout changes
- [ ] Code style changes (formatting, local variables)
- [ ] Refactoring (no functional changes)
- [ ] Build or CI related changes
- [ ] Tests
- [ ] Other... Please describe:

## What changes does this PR introduce?

## Screenshot of the affected changes

## Accessibility report

## Checklist

- [ ] I have updated the documentation accordingly
- [ ] I have confirmed all acceptance criteria defined by the story have been met
- [ ] I have confirmed that Sonar Qube findings for new code are reviewed and fixed, or will be whitelisted

2023-12-13 23:33 UTC, thechechogomez commented on libs/employer/feature/dashboard/src/lib/components/employer-detail/employer-detail.component.ts
>      switchMap(params => {
I'm not 100% sure about this switch map. We need to load the transactions either here or in the `employer-sub-category` component. My other option was a regular subscription after checking that the `transactionId` parameter exists, after assigning the `subCategories` to `this.subCategoryTabs`.

2023-12-13 23:34 UTC, thechechogomez commented on libs/employer/feature/dashboard/src/lib/components/employer-detail/employer-detail.component.ts
> +      const transactionId = params.get('transactionId') ?? '';
I'm not 100% sure about this switch map. We need to load the transactions either here or in the `employer-sub-category` component. My other option was a regular subscription after checking that the `transactionId` parameter exists, after assigning the `subCategories` to `this.subCategoryTabs`.

2023-12-13 23:45 UTC, thechechogomez commented on libs/employer/feature/dashboard/src/lib/components/employer-sub-category/employer-sub-category.component.ts
> -        this._router.navigate(['/dashboard', this.categoryRoute, subCategories[0].key], { replaceUrl: true });
Had to delete this line as it was interfering with the routing to the transaction. In the `category-routing` we route to the first category either way.

2023-12-14 03:54 UTC, thechechogomez commented on libs/employer/feature/dashboard/src/lib/components/employer-detail/employer-detail.component.ts
> +      const transactionId = params.get('transactionId') ?? '';
This does allow us to not show the component until the `loadingTransactionDetails$` observable is complete. Maybe there is a prettier way?

2023-12-14 16:26 UTC, derekdiep42 reviewed
Nice work with this!!! This is a huge PR but very clean.

The only biggish comment is to see if we can separate the category logic and the transaction logic into two separate observables, or maybe make it a bit prettier. I'll have to stare at the code for a bit to figure it out, but let's try to think about other ways for now?

2023-12-14 16:26 UTC, derekdiep42 commented on libs/employer/feature/dashboard/src/lib/components/employer-detail/employer-detail.component.html
> +    <div class="sub-section" *ngIf="!transaction">
I think we can remove this check. I think employer details are not tied to the transaction itself. There's a lot unknowns right now so maybe keep this part in regardless?

2023-12-14 16:26 UTC, derekdiep42 commented on libs/employer/feature/dashboard/src/lib/components/employer-detail/employer-detail.component.html
> +    <ng-container *ngIf="!transaction && (agentsSelectOptions$ | async) as agentsSelectOptions">
I believe there is an assigned agent for transactions so maybe leave this as well for now?

2023-12-14 16:26 UTC, derekdiep42 commented on libs/employer/feature/dashboard/src/lib/lib.routes.ts
> +        path: '',
i feel like the path at the bottom still makes it a little hard to read in these files, but maybe in a follow up ticket, arrange it so that page is first?

2023-12-14 16:26 UTC, derekdiep42 commented on libs/employer/feature/dashboard/src/lib/lib.routes.ts
> +const EmployerTransactionChildren = [
nice work with this! very neat!

2023-12-14 16:26 UTC, derekdiep42 commented on libs/employer/feature/dashboard/src/lib/components/employer-detail/employer-detail.component.ts
> +          this.transaction = transactionModel;
Yeah i was thinking if we separate it into separate observables, we wouldn't need to zip and stuff? If this can't be done than maybe find some way to use behavioural subjects to tell the application when to start checking for transactions? I don't like how everything is so cluttered here, there maybe is a more clean way.

2023-12-14 17:33 UTC, davidyoung77 commented on libs/employer/feature/dashboard/src/lib/components/confirmation/confirmation.component.html
> +<div class="dsg-confirmation__message">
Can this be moved to a shared component?

2023-12-14 17:34 UTC, davidyoung77 commented on libs/employer/feature/dashboard/src/lib/components/confirmation/confirmation.component.html
> +<div class="dsg-confirmation__message">
This could live in form-nuv

2023-12-14 17:46 UTC, davidyoung77 requested changes
Thanks really good work, I have a few changes

2023-12-14 17:46 UTC, davidyoung77 commented on libs/employer/feature/dashboard/src/lib/lib.routes.ts
> +    path: '',
Lets be consistent and move path above

2023-12-14 17:46 UTC, davidyoung77 commented on libs/employer/feature/dashboard/src/lib/lib.routes.ts
> +            path: ':subCategory',
Move above

2023-12-14 17:46 UTC, davidyoung77 commented on libs/employer/feature/dashboard/src/lib/components/confirmation/confirmation.component.html
> +<div class="dsg-confirmation__message">
I think we have the breadcrumb in public portal but if the rest is the same then this can be shared

2023-12-14 18:21 UTC, thechechogomez commented
<img width="952" alt="Screenshot 2023-12-14 at 1 13 06 PM" src="https://github.com/Nuvalence/dsgov-web/assets/60438413/422f7dad-8725-4065-b9f6-cf480773cb5e">
Confirmation view after changes to the **Public Portal**, no functional changes

2023-12-14 22:52 UTC, davidyoung77 approved these changes
Approved pending 1 minor comment, thanks.

2023-12-14 22:52 UTC, davidyoung77 commented on libs/shared/ui/nuverial/src/lib/components/transaction-confirmation/transaction-confirmation.component.ts
> +import { CommonModule } from '@angular/common';
This isn't really a nuverial component but makes more sense in the form-nuv library, can you move this?

2023-12-15 16:47 UTC, davidyoung77 approved these changes
Thanks, nice work

2023-12-15 17:17 UTC, merged