DSG-2655 fix: add function to reset page count when switching tabs/dashboards
Nuvalence/dsgov-web pull request #771
Opened 2024-01-10 21:18 UTC by benjaminlu-nuv

# Basics

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Styling and layout changes
- [ ] Code style changes (formatting, local variables)
- [ ] Refactoring (no functional changes)
- [ ] Build or CI related changes
- [ ] Tests
- [ ] Other... Please describe:

## What changes does this PR introduce?

## Screenshot of the affected changes

## Accessibility report

## Checklist

- [ ] I have updated the documentation accordingly
- [ ] I have confirmed all acceptance criteria defined by the story have been met
- [ ] I have confirmed that Sonar Qube findings for new code are reviewed and fixed, or will be whitelisted

2024-01-10 21:48 UTC, davidyoung77 requested changes

2024-01-10 21:48 UTC, davidyoung77 commented on libs/agency/feature/dashboard/src/lib/components/dashboard/dashboard.component.ts
> +      this.pagingRequestModel.resetToStart();
Do we need this in both places still?

2024-01-10 21:48 UTC, davidyoung77 commented on libs/shared/utils/http/src/lib/models/pagination/paging-request.model.ts
> +  }
A couple of things here:

- This navigation is being duplicated a bunch here we should to this in a private _function
- We should make this more reusable provide optional overrides in the reset method

```suggestion
  public reset(paging?: {
    pageNumber: 0,
    pageSize: 50,
    sortBy: '',
     sortOrder: 'ASC'
  }) {
    this.pageNumber = pageSize;
    this._router?.navigate([], {
      queryParams: { pageNumber: this.pageNumber, pageSize: this.pageSize, sortBy: this._sortBy, sortOrder: this.sortOrder } as Params,
      queryParamsHandling: 'merge',
      relativeTo: this._activatedRoute,
    });
  }
```

2024-01-11 15:25 UTC, davidyoung77 commented on libs/shared/utils/http/src/lib/models/pagination/paging-request.model.ts
> +    this._router?.navigate([], {
Since the params are handled in the setters here, I don't think you need the navigation in this method.

correct me if I am wrong

2024-01-11 15:27 UTC, davidyoung77 commented on libs/agency/feature/dashboard/src/lib/components/dashboard/dashboard.component.ts
> +      queryParams: { status: tab.tab.textLabel } as Params,
I'm thinking we should actually persist the params here, then we can also see in the url the pagination criteria also

2024-01-11 15:48 UTC, benjaminlu-nuv commented on libs/shared/utils/http/src/lib/models/pagination/paging-request.model.ts
> +    this._router?.navigate([], {
yes you are right, I will fix this

2024-01-11 15:49 UTC, benjaminlu-nuv commented on libs/agency/feature/dashboard/src/lib/components/dashboard/dashboard.component.ts
> +      queryParams: { status: tab.tab.textLabel } as Params,
I was thinking that since reset will set the page number to 0 anyway, it would make the call to the setter to change the url but I just checked and it doesn't - will fix this as wel

2024-01-12 16:11 UTC, benjaminlu-nuv commented on libs/agency/feature/dashboard/src/lib/components/dashboard/dashboard.component.ts
> +      this.pagingRequestModel.resetToStart();
yes reset should be called for both changing tabs and dashboards here

2024-01-12 16:31 UTC, thechechogomez reviewed
Looks good. Just a small change. I'll let @davidyoung77 give the final say on this.

2024-01-12 16:31 UTC, thechechogomez commented on libs/employer/feature/dashboard/src/lib/components/account-access/user-list/user-list.component.ts
> +                this.pagingRequestModel.reset();
nit: I know I said to use the reset here, but thinking it over we don't want the user to go to the first page or change the pagination, we just want to refresh the view.

2024-01-12 16:31 UTC, thechechogomez commented on libs/employer/feature/dashboard/src/lib/components/account-access/user-list/user-list.component.ts
> +                this.pagingRequestModel.reset();
nit: Same here. Let's not reset any parameter on the paging request model.

2024-01-12 16:45 UTC, benjaminlu-nuv commented on libs/employer/feature/dashboard/src/lib/components/account-access/user-list/user-list.component.ts
> +                this.pagingRequestModel.reset();
Ok no problem, we can still use the reset function except pass in the parameters we want to keep

2024-01-12 16:45 UTC, benjaminlu-nuv commented on libs/employer/feature/dashboard/src/lib/components/account-access/user-list/user-list.component.ts
> +                this.pagingRequestModel.reset();
same here, I will still call the reset function but keep all parameters except for pageNumber

2024-01-12 16:51 UTC, davidyoung77 commented on libs/employer/feature/dashboard/src/lib/components/account-access/user-list/user-list.component.ts
> +                this.pagingRequestModel.reset();
If we are keeping all of them, no need to reset

2024-01-12 16:53 UTC, benjaminlu-nuv commented on libs/employer/feature/dashboard/src/lib/components/account-access/user-list/user-list.component.ts
> +                this.pagingRequestModel.reset();
I misunderstood, if we are also not resetting pageNumber I will remove the function calls here then

2024-01-12 17:08 UTC, davidyoung77 reviewed
Nice work this is almost there, I left a few additional comments

2024-01-12 17:08 UTC, davidyoung77 commented on libs/shared/utils/http/src/lib/models/pagination/paging-request.model.ts
> +    queryParams['sortOrder'] = this._sortOrder !== 'ASC' ? this._sortOrder : null;
You can use the or operator rather than the ternary if you want.

```suggestion
    queryParams['pageNumber'] = this._pageNumber || null;
    queryParams['pageSize'] = this._pageSize !== pageSizeOptions[0] ? this._pageSize : null;
    queryParams['sortBy'] = this._sortBy || null;
    queryParams['sortOrder'] = this._sortOrder || null;
```

2024-01-12 17:08 UTC, davidyoung77 commented on libs/shared/utils/http/src/lib/models/pagination/paging-request.model.ts
> +  private _pageSize = pageSizeOptions[0];
I'm ok if this is updated to 10 rather than 50, but please verify that the implementations that are defaulting to 50 are updated

2024-01-12 20:21 UTC, davidyoung77 approved these changes
Looks good approved

2024-01-12 21:23 UTC, merged