Dsg 2692/ada html titles agency
Nuvalence/dsgov-web pull request #807
Opened 2024-01-22 19:28 UTC by sunnyjiao-nv

# Basics

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Styling and layout changes
- [ ] Code style changes (formatting, local variables)
- [ ] Refactoring (no functional changes)
- [ ] Build or CI related changes
- [ ] Tests
- [ ] Other... Please describe:

## What changes does this PR introduce?
Introduces dynamic setting of the HTML <title> tag for ADA purposes.
Uses a new `TitleService` that wraps the Angular `Title` service to set the name of the Portal, and the title of the HTML.

HTML tags are set in:
- Dashboard: `Public portal`
- Transaction form viewer: `TransactionDefinitionName - Step Name/Application Submitted/Review`

## Screenshot of the affected changes

## Accessibility report

## Checklist

- [ ] I have updated the documentation accordingly
- [ ] I have confirmed all acceptance criteria defined by the story have been met
- [ ] I have confirmed that Sonar Qube findings for new code are reviewed and fixed, or will be whitelisted

2024-01-22 22:32 UTC, sunnyjiao-nv commented on libs/public/feature/dashboard/src/lib/components/dashboard/dashboard.component.ts
> +    this._titleService.setPortalTitle('Public');
Agreed, this doesn't seem right.

I think the idea was that on startup, each portal app can set their `portalName` using the service, and if we were to eventually make `dashboard` a shared component, we can set the HTML title via something like `titleService.setHtmlTitle('${portalName} - Dashboard')`. I was thinking that maybe this TitleService should be in `shared/utils` after all, or somewhere where the root `app.component` of each portal can access. That way, we can set the `portalName` there and let the dashboard components just retrieve the name and set the HTML title.

I don't think there's anywhere else right now where setting/getting the portal name is useful but I imagine that there might be cases later where a dumb UI component may need to know which Portal it's instantiated in

2024-01-23 15:24 UTC, sunnyjiao-nv commented on libs/public/feature/dashboard/src/lib/components/dashboard/dashboard.component.ts
> +    this._titleService.setPortalTitle('Public');
I've changed it to this: The setting of `portalTitle` is now done in the `shell.component`. Then, the Dashboard and Profile components set the `htmlTitle` via:
```javascript
this._titleService.portalTitle$
      .pipe(
        take(1),
        tap(portalTitle => this._titleService.setHtmlTitle(`${portalTitle} portal - Dashboard`)),
      )
      .subscribe();
```

2024-01-23 17:47 UTC, davidyoung77 requested changes
Thanks, I have some comments

2024-01-23 17:47 UTC, davidyoung77 commented on libs/public/feature/dashboard/src/lib/components/dashboard/dashboard.component.ts
> +// import { TitleService } from '@dsg/shared/utils/title';
commented code

2024-01-23 17:47 UTC, davidyoung77 commented on libs/shared/ui/nuverial/src/lib/services/title/title.service.ts
> +  }
Rather than having a public method for this what if we make this self contained and handle this in the constructor

```suggestion
  constructor(private readonly _ngTitleService: Title) {
    this._portalTitle.next(this._ngTitleService.getTitle())
  }
```

2024-01-23 17:47 UTC, davidyoung77 commented on libs/shared/feature/form-nuv/src/lib/components/steps/formly/formly-steps.component.ts
> +    this._formRendererService.transaction$
Since the transaction will always be loaded here you can simplify this with:

`this._titleService.setHtmlTitle(`${this._formRendererService.transaction.transactionDefinitionName} - ${field?.props?.label}`))`

You should be able to do the same in other areas

2024-01-23 17:47 UTC, davidyoung77 commented on libs/public/feature/profile/src/lib/components/profile/profile.component.ts
> +      .subscribe();
You should update your service method, with an optional boolean property `includePortalTitle` to be able to easier handle this

2024-01-23 17:47 UTC, davidyoung77 commented on libs/public/feature/dashboard/src/lib/components/confirmation/confirmation.component.ts
> +      .pipe(
Since the transaction will always be loaded here you can simplify this with:

this._titleService.setHtmlTitle(${this._formRendererService.transaction.transactionDefinitionName} - ${field?.props?.label}))

You should be able to do the same in other areas

2024-01-23 17:47 UTC, davidyoung77 commented on libs/public/feature/dashboard/src/lib/components/dashboard/dashboard.component.ts
> +    this._titleService.portalTitle$
Since the transaction will always be loaded here you can simplify this with:

this._titleService.setHtmlTitle(${this._formRendererService.transaction.transactionDefinitionName} - ${field?.props?.label}))

You should be able to do the same in other areas

2024-01-23 17:47 UTC, davidyoung77 commented on libs/public/feature/dashboard/src/lib/components/dashboard/dashboard.component.ts
> +    this._titleService.portalTitle$
Should we reset the titles in ngondestroy so the title still looks right if it is not applied on a specific route?

2024-01-24 15:45 UTC, davidyoung77 approved these changes
Approved pending comments

2024-01-24 15:45 UTC, davidyoung77 commented on libs/shared/ui/nuverial/src/lib/services/title/title.service.ts
> +  public setHtmlTitle(title: string, includePortalTitle?: boolean): void {
Add documentation to public properties

2024-01-24 17:10 UTC, davidyoung77 approved these changes

2024-01-24 19:43 UTC, davidyoung77 approved these changes
This is great approved

2024-01-24 19:44 UTC, merged