DSG-2793: sort rejected documents
Nuvalence/dsgov-web pull request #830
Opened 2024-01-29 22:11 UTC by lucywang-nv

# Basics

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Styling and layout changes
- [ ] Code style changes (formatting, local variables)
- [ ] Refactoring (no functional changes)
- [ ] Build or CI related changes
- [ ] Tests
- [ ] Other... Please describe:

## What changes does this PR introduce?
Sort the rejected documents so that it reflects the order in the form.

Note: Used recursion in _getDocumentKey for dynamic form configs. For example, for financial benefit the key is nested 4 levels but in Unemployment insurance it's 3 levels:
![image](https://github.com/Nuvalence/dsgov-web/assets/156008540/0cf69677-098f-43e3-8d52-fffbc02bb7b0)
![image](https://github.com/Nuvalence/dsgov-web/assets/156008540/2470cf87-dff7-4043-8117-67d34e6d9f16)

## Screenshot of the affected changes
Before: 
![Before](https://github.com/Nuvalence/dsgov-web/assets/156008540/b31f9427-933d-4a45-93df-c9e9025a8fb5)
![Before-FinancialBenefit](https://github.com/Nuvalence/dsgov-web/assets/156008540/a222a797-6177-4230-a499-ec44a07a7635)

After:
![After](https://github.com/Nuvalence/dsgov-web/assets/156008540/bdd5f109-746c-4790-a7ca-ff661f4bc405)
![After - FinancialBenefit](https://github.com/Nuvalence/dsgov-web/assets/156008540/666c0a6d-a0eb-4d98-bc93-cec2563a8377)

## Accessibility report

## Checklist

- [ ] I have updated the documentation accordingly
- [ ] I have confirmed all acceptance criteria defined by the story have been met
- [ ] I have confirmed that Sonar Qube findings for new code are reviewed and fixed, or will be whitelisted

2024-01-30 20:28 UTC, kevincheng0 requested changes
Looks good, just some changes in order to make it general to any transaction

2024-01-30 20:28 UTC, kevincheng0 commented on libs/public/feature/dashboard/src/lib/services/dashboard.service.ts
> +        .filter(comp => comp.key === 'attachments' || comp.key === 'documents')
The component key doesn't determine the type of that component. For example, a transaction can have a component with the key 'identification', that contains various file upload components. In this case, 'attachments' and 'documents' are the keys that we chose for FinancialBenefit or UnemploymentInsurance. They way to identify the type of a component is if the `type` property is `nuverialFileUpload` or `nuverialMultipleFileUpload`. DFS through the transaction model can work, and you can probably get the key of each component along the way. Or maybe a deep filter and flatten.

2024-01-30 20:28 UTC, kevincheng0 commented on libs/public/feature/dashboard/src/lib/services/dashboard.service.ts
> +  private _sortRejectedDocuments(sortOrder: string[], firstDoc: RejectedDocument, secondDoc: RejectedDocument) {
We should probably consider the order of documents in a multiple document upload component. Each `RejectedDocument` has an `index` property, and we should compare those as well.

2024-01-31 15:11 UTC, lucywang-nv commented on libs/public/feature/dashboard/src/lib/services/dashboard.service.ts
> +        .filter(comp => comp.key === 'attachments' || comp.key === 'documents')
Made the change, using DFS.

2024-01-31 15:12 UTC, lucywang-nv commented on libs/public/feature/dashboard/src/lib/services/dashboard.service.ts
> +  private _sortRejectedDocuments(sortOrder: string[], firstDoc: RejectedDocument, secondDoc: RejectedDocument) {
Changed.

2024-01-31 15:42 UTC, kevincheng0 approved these changes
Looks good :)

2024-01-31 16:00 UTC, davidyoung77 approved these changes

2024-01-31 16:42 UTC, merged