Dsg 2842/focus not reset
Nuvalence/dsgov-web pull request #854
Opened 2024-02-05 22:21 UTC by benjaminlu-nuv

# Basics

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Styling and layout changes
- [ ] Code style changes (formatting, local variables)
- [ ] Refactoring (no functional changes)
- [ ] Build or CI related changes
- [ ] Tests
- [ ] Other... Please describe:

## What changes does this PR introduce?

Now focuses on the current step of the intake form instead of focus staying on the button clicked
## Screenshot of the affected changes
https://www.loom.com/share/7f660c23afed498b843905c33880c8f3

## Accessibility report

## Checklist

- [ ] I have updated the documentation accordingly
- [ ] I have confirmed all acceptance criteria defined by the story have been met
- [ ] I have confirmed that Sonar Qube findings for new code are reviewed and fixed, or will be whitelisted

2024-02-05 23:16 UTC, davidyoung77 commented on libs/shared/ui/nuverial/src/lib/components/stepper/stepper.component.ts
> +    const stepHeaders = this._elementRef.nativeElement.querySelectorAll('.mat-horizontal-stepper-header, .mat-vertical-stepper-header');
This looks good, just wondering if there is a better selector we can target, maybe something we own so that we know it won't change like `active-step`? we could add this on the nuverial component if it doesn't already have it?

2024-02-06 02:37 UTC, benjaminlu-nuv commented on libs/shared/ui/nuverial/src/lib/components/stepper/stepper.component.ts
> +    const stepHeaders = this._elementRef.nativeElement.querySelectorAll('.mat-horizontal-stepper-header, .mat-vertical-stepper-header');
I couldn't find a way to dynamically add something to each mat-step, however I changed the way we select to use aria-selected as that is something less likely to change - please let me know if this is an alright workaround

2024-02-06 15:57 UTC, davidyoung77 commented on libs/shared/ui/nuverial/src/lib/components/stepper/stepper.component.ts
> +            const activeStepHeader = document.querySelector('.mat-step-header[aria-selected="true"]');
This still targets the mat step class that we don't own

2024-02-06 15:59 UTC, davidyoung77 requested changes

2024-02-06 19:23 UTC, davidyoung77 approved these changes

2024-02-06 19:24 UTC, merged