DSG-2803: attachments for secure messages
Nuvalence/dsgov-web pull request #863
Opened 2024-02-08 15:43 UTC by kevincheng0

# Basics

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Styling and layout changes
- [ ] Code style changes (formatting, local variables)
- [ ] Refactoring (no functional changes)
- [ ] Build or CI related changes
- [ ] Tests
- [ ] Other... Please describe:

## What changes does this PR introduce?

## Screenshot of the affected changes

## Accessibility report

## Checklist

- [ ] I have updated the documentation accordingly
- [ ] I have confirmed all acceptance criteria defined by the story have been met
- [ ] I have confirmed that Sonar Qube findings for new code are reviewed and fixed, or will be whitelisted

2024-02-08 18:13 UTC, davidyoung77 reviewed
Nice work, approved pending comments

2024-02-08 18:13 UTC, davidyoung77 commented on libs/shared/feature/documents/src/lib/components/rich-text-editor-attachment/rich-text-editor-attachment.component.ts
> +    this._uploading$.subscribe();
We should include a `take(1)`

2024-02-08 18:13 UTC, davidyoung77 commented on libs/shared/feature/documents/src/lib/components/rich-text-editor-attachment/rich-text-editor-attachment.component.ts
> +        .subscribe();
forgot to manage unsubscribing

2024-02-08 18:13 UTC, davidyoung77 commented on libs/shared/feature/documents/src/lib/services/file-upload.service.ts
> +    return this._documentFormService.getProcessingResultsById$(documentId).pipe(
I've been thinking about a better name for `documentFormService` What do you think about `documentUploadService`?

2024-02-08 18:44 UTC, kevincheng0 commented on libs/shared/feature/documents/src/lib/components/rich-text-editor-attachment/rich-text-editor-attachment.component.ts
> +        .subscribe();
is it better form to manage unsubscribing in the service or in the component? I have `take(1)` in the service

2024-02-08 18:45 UTC, kevincheng0 commented on libs/shared/feature/documents/src/lib/components/rich-text-editor-attachment/rich-text-editor-attachment.component.ts
> +    this._uploading$.subscribe();
it has to continue being subscribed since uploading status can change multiple times

2024-02-08 18:49 UTC, kevincheng0 commented on libs/shared/feature/documents/src/lib/services/file-upload.service.ts
> +    return this._documentFormService.getProcessingResultsById$(documentId).pipe(
Maybe just `documentService` since it manages a lot of different document API calls?

2024-02-09 15:39 UTC, davidyoung77 approved these changes
approved pending comments

2024-02-09 15:39 UTC, davidyoung77 commented on libs/shared/feature/documents/src/lib/components/rich-text-editor-attachment/rich-text-editor-attachment.component.ts
> +        .subscribe();
It is better to manage it where you subscribe, that way its easy to read

2024-02-09 15:42 UTC, davidyoung77 requested changes
A couple changes

2024-02-09 15:42 UTC, davidyoung77 commented on libs/shared/feature/documents/src/lib/components/rich-text-editor-attachment/rich-text-editor-attachment.component.ts
> +    this._uploading$.subscribe();
Then we need to use `untilDestroyed(this)` otherwise we will have a memory leak

2024-02-09 15:43 UTC, kevincheng0 commented on libs/shared/feature/documents/src/lib/components/rich-text-editor-attachment/rich-text-editor-attachment.component.ts
> +    this._uploading$.subscribe();
untilDestroyed(this) is in the pipe for _uploading$, i'll move it out so it's more readable

2024-02-09 15:59 UTC, davidyoung77 approved these changes

2024-02-09 16:13 UTC, merged