Dsg 2945/date range two fields
Nuvalence/dsgov-web pull request #900
Opened 2024-02-21 21:05 UTC by sunnyjiao-nv

# Basics

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Styling and layout changes
- [ ] Code style changes (formatting, local variables)
- [ ] Refactoring (no functional changes)
- [ ] Build or CI related changes
- [ ] Tests
- [ ] Other... Please describe:

## What changes does this PR introduce?
- Modifies the Date Range Component so that instead of mapping to a single `localDate` key with a child `startDate` and `endDate`, we require two `localDate` keys representing the start and end.
- Specifically, the `nuverial-date-range` component still holds a `formControl` with a `startDate` and `endDate`. But the Formly component will separately handle mapping of those to the user selected `localDate` Schema Keys

## Screenshot of the affected changes

https://github.com/Nuvalence/dsgov-web/assets/155997897/596929a4-561e-4607-87de-bdbde55d0e35

## Accessibility report

## Checklist

- [ ] I have updated the documentation accordingly
- [ ] I have confirmed all acceptance criteria defined by the story have been met
- [ ] I have confirmed that Sonar Qube findings for new code are reviewed and fixed, or will be whitelisted

2024-02-22 16:18 UTC, kevincheng0 commented on libs/shared/feature/form-nuv/src/lib/components/date-range-picker/formio/formio-date-range-picker.model.ts
> +  key: 'components',
I feel like we should change this key to something more descriptive. Maybe "dates," and update the schema in line 32 as well

2024-02-22 16:29 UTC, davidyoung77 commented on libs/shared/feature/form-nuv/src/lib/components/date-range-picker/formly/formly-date-range-picker.component.ts
> +  public onDateChange(event: DateRangePickerControl) {
I want to look at this a little more

2024-02-22 16:31 UTC, kevincheng0 commented on libs/shared/feature/form-nuv/src/lib/components/date-range-picker/formly/formly-date-range-picker.component.ts
> +  public onDateChange(event: DateRangePickerControl) {
Instead of using a handler to set the dateControl value, you can subscribe to `this.dateControl.valueChanges` observable since the child component already receives and updates `dateControl`

2024-02-22 16:34 UTC, kevincheng0 commented on libs/shared/feature/form-nuv/src/lib/components/date-range-picker/formly/formly-date-range-picker.component.ts
> +        this.dateControl.setValue({
Would it be better to store a variable with `dateControl` value then update it all at once to avoid setting the value twice?

2024-02-22 16:35 UTC, kevincheng0 commented on libs/shared/ui/nuverial/src/lib/components/date-picker/date-range-picker.component.ts
> +    this.dateChange.emit({ endDate: transformedEnd, startDate: transformedStart } as DateRangePickerControl);
If you set formControl value here, you can avoid using an event emitter.

2024-02-22 16:36 UTC, kevincheng0 commented on libs/shared/feature/form-nuv/src/lib/components/date-range-picker/formly/formly-date-range-picker.component.ts
> +  public onDateChange(event: DateRangePickerControl) {
I added some comments related to this @davidyoung77

2024-02-22 17:19 UTC, davidyoung77 requested changes

2024-02-22 17:19 UTC, davidyoung77 commented on libs/shared/feature/form-nuv/src/lib/components/date-range-picker/formly/formly-date-range-picker.component.html
> +    (dateChange)="onDateChange($event)"
You shouldn't need this, you have the value in the formControl, you can subscribe to form control changes if needed

2024-02-22 17:19 UTC, davidyoung77 commented on libs/shared/ui/nuverial/src/lib/components/date-picker/date-range-picker.component.ts
> +  @Output() public readonly dateChange = new EventEmitter<DateRangePickerControl>();
Like @kevincheng0 pointed out, you wont need this emitter

2024-02-22 17:47 UTC, sunnyjiao-nv commented on libs/shared/feature/form-nuv/src/lib/components/date-range-picker/formio/formio-date-range-picker.model.ts
> +  key: 'components',
If I change it away from 'components' the datagrid stops rendering all the rows, I'm not exactly sure why. That goes for the Address and Upload File components too

2024-02-22 21:04 UTC, davidyoung77 approved these changes

2024-02-22 21:15 UTC, davidyoung77 approved these changes
Approved pending comment

2024-02-22 21:15 UTC, davidyoung77 commented on libs/shared/feature/form-nuv/src/lib/components/date-range-picker/formio/formio-date-range-picker.model.ts
> +  components: [
We discussed @sunnyjiao-nv moving this to props.startKey and props.endKey

2024-02-26 22:00 UTC, davidyoung77 commented on libs/shared/feature/form-nuv/src/lib/components/date-range-picker/formio/formio-date-range-picker.model.ts
> +  key: 'components[0].key',
If you do it like this you don't need an array of components
```suggestion
  key: 'props.startDateKey',
```

2024-02-27 17:52 UTC, davidyoung77 commented on libs/shared/feature/form-nuv/src/lib/components/date-range-picker/formly/formly-date-range-picker.component.ts
> +
Maybe add some context explaining why we create the fields here

2024-02-27 17:52 UTC, davidyoung77 approved these changes
Looks good

2024-02-27 18:17 UTC, kevincheng0 approved these changes

2024-02-27 18:18 UTC, merged